keys:
  default:
    task1:
      commands:
        - give {name} diamond 50
    task2:
      commands:
        - kill {name}
#These values should not be changed under any circumstances. Leave them be.
crates:
  crate1:
    X: 1
    Y: 1
    Z: 1
    world: 'world'
    type: