main: red.reddington.crates.Crates
name: Crates
version: 0.0.3
author: RenegadeEagle
commands:
  crates:
    description: Base command for crates
  cmessage:
    description: Command to send players messages raw.
  keys:
    description: Key methods to add/take keys